### ISSUE TITLE
Hyperlink to source system incident details is broken

### ISSUE THREAD

**Issue by lunkwill42** [Uninett/Argus-frontend#125]
As mentioned in https://github.com/Uninett/Argus-frontend/issues/93#issuecomment-692638392, the hyperlink to the source system's incident details on the incident details model is broken.

The Incident record itself may contain relative URLs. If a URL is not a fully qualified URL, the hyperlink should be constructed using the `base_url` present in the source system definition as a prefix. Example output from the Incident endpoint:

```json
[
  {
    "pk": 18,
    "start_time": "2020-09-14T17:06:49.983721+02:00",
    "end_time": "infinity",
    "source": {
      "pk": 1,
      "name": "testnav",
      "type": {
        "name": "nav"
      },
      "user": 2,
      "base_url": "http://localhost:9080/"
    },
    "source_incident_id": "199420",
    "details_url": "/search/event/199420",
    "description": "Link DOWN on A1 at example-sw.example.org (4.kx042)",
    "ticket_url": "",
    "tags": []
  }
]
```

The URL **may** also be a fully qualified URL, in which case it is ok to use it unchanged.

**Comment by hmpf** [comment]
See https://github.com/Uninett/Argus/pull/161 and https://github.com/Uninett/Argus/issues/50.

Once https://github.com/Uninett/Argus/pull/161 is merged, the filterable incident endpoints will send three different types of `details_url`s:

* Empty string
* Relative url, because the source system does not have base_url set, and the source sends relative urls
* Absolute url

I don't thin linkifying relative urls is a good idea. I'll make a polish-ticket for it.
