### ISSUE TITLE
Filter preview does not work

### ISSUE THREAD

**Issue by lunkwill42** [Uninett/Argus-frontend#146]
When constructing a filter in the frontend, there is a button to preview the filter, i.e. show which existing incidents it matches.

However, this preview button fetches and displays **all** incidents, as it calls the `/incidents/` endpoint without any filter arguments.

This **must** be fixed before 1.0, as there is no point to the function if it does not work as advertised.

**Comment by jorgenbele** [comment]
This seems to have been fixed implicitly in #147 when I updated to cursor pagination. I am not able to replicate this on #147.

**Comment by lunkwill42** [comment]
Current deployment, with master on both back- and frontends does not seem to work for me, @jorgenbele. The frontend issues a request to the incidents endpoint when the preview button is clicked, and a response is retrieved, but no results are shown in the interface...

**Comment by hmpf** [comment]
I note that filtering on tags doesn't seem to work. Also, when you save a filter, the tags aren't saved with it (or: not shown as saved in the list of saved filters.)

**Comment by hmpf** [comment]
After having added another source to my server running on localhost, currently it doesn't seem to work for sources either. though the source saves properly.

**Comment by hmpf** [comment]
The format of filter_string is currently:

```
{
  "sourceSystemIds": [] | [
     int,
    ..
  ],
  "tags": [] | [
     "key1=value1",
     "key1=value2",
     "key2=value3",
     ..
  ]
}
```

So: all values are either an empty list/array or a list/array of key-specific type.

The currently planned extensions would make it look like:

```
{
  "sourceSystemIds": [] | [
     int,
     ..
  ],
  "tags": [] | [
     "key1=value1",
     "key1=value2",
     "key2=value3",
     ..
  ],
  "sourceSystemTypeIds": [] | [
     int,
     ..
  ],
  "stateful": true | false | null,
  "open": true | false | null,
  "acked": true | false | null,
}
```

.. the safe approach would be to treat it as a hash/dict which may have some unknown keys, and not touch those. That way, we can add filter-options to the backend without having to keep the frontend in lock-step. `null` will be used for "both/all" unless you have better ideas. 

Since it is stored as a string in the backend we can still change things very freely. It'd make more sense to store it as JSON though (and add a proper serializer and form for it), but we should wait until an upgrade to Django 3.1 for that and the native field support.

There's also (but maybe not for 1.1) an extension that flips the filter from inclusive to exclusive but we haven't settled for a name for that key yet. That would be: `"somekey": true | false`.

**Comment by hmpf** [comment]
The inclusive/exclusive toggle might just be an independent, separate field too.

**Comment by hmpf** [comment]
Fix has been merged, closing.
