### ISSUE TITLE
Bug: Feide logout does not work

### ISSUE THREAD

**Issue by lunkwill42** [Uninett/Argus-frontend#175]
**Describe the bug**
If logging in to Argus using Feide, I cannot properly log out again. 

* If I select the "Log out" menu item, I am simply sent to the login URL. If change the URL to go back to the front page of Argus, I am still logged in as my Feide user.
* Event worse: If I log out, and then attempt to log back in using a *local* username/password combination, once I get back in to the Argus front page, Argus still thinks I am logged in as my Feide user.

**To Reproduce**
Trivially reproduced from the description above.

**Expected behavior**
When I click log out, I expect to be permanently logged out and not able to use Argus again until I log in again. I also expect to be logged in as the user whose credentials I supply, not as someone else, which is a potential security issue!

**Comment by jorgenbele** [comment]
This seems to be an issue regarding how cookies are deleted on logout. When there are more than one cookie from the same domain (which happens in some circumstances apparently), it only removes one of them. I'll have to investigate some more to find out the issue here, but note that this is not reproducible in the development setup.

**Comment by hmpf** [comment]
Possibly connected to #79 and #322
