### ISSUE TITLE
Bug: RangeError: Invalid time value in Safari

### ISSUE THREAD

**Issue by lunkwill42** [Uninett/Argus-frontend#261]
**Describe the bug**
This one is from our Swedish colleagues in SUNET, who are testing Argus:

When browsing the frontend with Safari set to a Swedish locale, the Incident details dialog crashes with the error message
> RangeError: Invalid time value

**To Reproduce**
1. Switch to Swedish locale in macOS
2. Browse Argus using Safari
3. Click on any incident

**Expected behavior**
The incident details dialog should show as normal.

**Screenshots**
![Skärmavbild 2021-05-12 kl  10 11 51](https://user-images.githubusercontent.com/100995/117941619-940f2f00-b30a-11eb-8695-7623071e2c56.png)

**Desktop (please complete the following information):**
 - OS: macOS Big Sur 11.2.3
 - Browser: Safari 14.0.4

**Additional context**
This may potentially be linked to #257, which also is Safari-related

**Comment by podliashanyk** [comment]
Reproduced the bug. Error occurs in Safari with any locale.

**Comment by podliashanyk** [comment]
Bug occurred due to invalid timestamp string passed to Date() constructor. 
Timestamp string has to comply with either [RFC 2822](https://datatracker.ietf.org/doc/html/rfc2822#page-14), or  [ISO 8601](https://262.ecma-international.org/11.0/#sec-date.parse). 

Example: passing a string '2011-11-11 10:11' causes RangeError. 
Fix: either convert the given string to '2011-11-11T10:11', or use date-fns' parseISO() instead of Date() constructor.
