### ISSUE TITLE
Make interval updates more user friendly

### ISSUE THREAD

**Issue by stveit** [Uninett/Argus-frontend#323]
### Problem
With Argus in Interval mode updating, the list of incidents refreshes in a way that is annoying for the user. 
This happens even if there is no changes made to the list of incidents that is currently viewed.
The refresh hinders work as certain actions cannot be done while this is happening, such as selecting incidents.
The visual noise is also annoying, as the refresh happens quite often.

### Possible solution
Only update the view if there is a change relevant to the current filter (new incidents or changes to existing incidents)

**Comment by podliashanyk** [comment]
> The refresh hinders work as certain actions cannot be done while this is happening, such as selecting incidents.

Suggest turning update when user:

- opens Incident detail view
- has at least 1 incident checked (includes user performing any of the bulk operations)

**Comment by podliashanyk** [comment]
> With Argus in Interval mode updating, the list of incidents refreshes in a way that is annoying for the user.
> This happens even if there is no changes made to the list of incidents that is currently viewed.

> ### Possible solution
> Only update the view if there is a change relevant to the current filter (new incidents or changes to existing incidents)

View update triggered only by changes relevant to the current filter are already implemented. User can use this functionality by switching to "Realtime" mode.

**Comment by podliashanyk** [comment]
> The visual noise is also annoying, as the refresh happens quite often.

User can change the refresh interval in the config-file. 

Consider also adding refresh interval modification to /settings as a more user friendly option?

**Comment by lunkwill42** [comment]
> > The refresh hinders work as certain actions cannot be done while this is happening, such as selecting incidents.
> 
> Suggest turning update off when user:
> 
>     * opens Incident detail view
> 
>     * has at least 1 incident checked (includes user performing any of the bulk operations)

I think this idea has merit, and would definitely like to see it implemented. But it only solves *some* of the usability problems. The current refresh that works like "blank everything, reload, then re-display" is still jarring if you are attempting to read off the screen.

**Comment by lunkwill42** [comment]
So, two potential solutions, beyond #328, were discussed IRL, in order to solve the jarring UX of blankout-and-redraw. I'll try to summarize them in writing:

1. A a quick-win might be for the refresh function to render the new result list off-screen and then replace the currently displayed list with the off-screen one. This animation-inspired technique may cause the blink effect to disappear, or at least minimized.

2. Re-use the framework that is used to render incident updates when the realtime function is enabled. I.e., when the incident list is re-fetched, instead of rendering a new list, use the fetched list to make incremental changes to the existing list.

@podliashanyk  will look into both solutions. Solution 1 might be a quick fix, solution 2 might need a more thorough work estimate.
