### ISSUE TITLE
Bug: the pages goes into the negative

### ISSUE THREAD

**Issue by Wiggen94** [Uninett/Argus-frontend#339]
**Describe the bug**
If the user click on the "previous page" arrow fast enough you can go way past "page 1" all the way to -1000 if the user clicks fast enough.

**To Reproduce**
1. Click on the next page arrow on the bottom right 2 times
2. Click rapidly on the "previous page"-icon and you will see that you can go all the way to the negative side.

**Expected behavior**
Expected to stop at the first page

**Screenshots**
![argus](https://user-images.githubusercontent.com/13270464/139810537-c8810044-41c4-43ff-a28d-4c048cc68fed.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 95

**Comment by podliashanyk** [comment]
@Wiggen94 Thank you for the bug report!

**Comment by podliashanyk** [comment]
## Additionally:

**Bug description**
If the user clicks on the "next page" arrow fast enough, the incidents count is way past the actual number of incidents. 

**To Reproduce**
Steps to reproduce the behavior:
1. Click rapidly on the next page arrow on the bottom right until you reach the last page.2. 
2. See that incidents count that is displayed is way higher than the actual one.

**Expected behavior**
Expected to display the actual number of incidents, regardless of how fast the user clicks on the "next page" arrow.

**Screenshots**
The actual number of incidents in the system is 400:
<img width="419" alt="Screenshot 2022-06-10 at 11 44 28" src="https://user-images.githubusercontent.com/60876078/173038806-24e260da-998a-4ad2-959b-3fe7bd2884f3.png">


Number of incidents if user clicks "next page" fast enough:
<img width="467" alt="Screenshot 2022-06-10 at 11 37 45" src="https://user-images.githubusercontent.com/60876078/173038591-0db4c8a9-02a0-4856-857f-1f510a4008b9.png">



**Desktop (please complete the following information):**
 - OS: macOS 12.4 Monterey
 - Browser: Chrome 102 (Same result in Safari 15.5 and Firefox 101)
 - Argus frontend version: 1.5.4
 - Argus backend version: 1.5.1
