### ISSUE TITLE
There should be a way of seeing a list of filters that exists, and deleting them should be possible.

### ISSUE THREAD

**Issue by jorgenbele** [Uninett/Argus-frontend#73]
As of now there is no way to see the created filters without creating a new notification profile and trying to add filters to it. Also, there is currently no way of deleting any filters.

Proposal:
- Display a table/list of filters on the `Filters` page

**Comment by hmpf** [comment]
Is this "filters created by user X" or "all filters"? (Are filters owned, and should they be shared?) IIRC shared filters is a problem in NAV, but maybe cloning filters should work?

**Comment by ddabble** [comment]
When we created the current model, we explicitly decided that sharing filters should not be possible - apart from exporting and importing filters, which would be the same as "cloning", I presume.

**Comment by lunkwill42** [comment]
NAV ships with a bunch of predefined filters. These are shared, and this was on purpose, since these basic filters provide useful functionality for all users as they are building their first alert profiles.

The weakness of this model, however, is that the admin can always edit shared filters, thereby changing the behavior of any user profile that employs this filter. This has happened on several occasions, and it really trips up users - the filter may have kept its old name, but have come to mean something different entirely - but users usually go by the face value of the filter name.

My alternative suggestion would perhaps be that filters **can** be shared, but a shared filter cannot be used in someone else's profile - it must be cloned first (i.e. shared filters only function as "usage examples" or "inspiration", if you will).
